[Feature] Implement `expect.each().resolves` and `.rejects` as prototype
openreachtech/jest-expect-each pull request #9
Opened 2022-05-02 21:12 UTC by StewEucen

## Why

* See #7 

## How

* Implement `expect.each().resolves` and `.rejects`.

## Note

* This is just prototype of 'expect.each()'.

* When it is OK, must add more test cases for other matcher of Jest.

2022-05-03 14:59 UTC, JYama321 approved these changes
🐄

2022-05-07 01:26 UTC, EG-easy approved these changes
🍵

2022-05-08 14:12 UTC, lisadhl requested changes

2022-05-08 14:12 UTC, lisadhl commented on lib/setup.js
> +      }
@StewEucen 

The implementation is very great! I took a long time to understand it.

I have a suggestion for invocation signature:

```js
JestExtender
  .forEach(actualTable)
  .expect
  .not
  .toBe(expectedValues)
```

Eg. [expect.any(constructor)](https://jestjs.io/docs/next/expect#expectanyconstructor) is some type of matcher, so I feel `expect.each` seems a few unnatural.

2022-05-08 14:12 UTC, lisadhl commented on lib/setup.js
> +  expect.each = (actualTable) => new Proxy(expect, {
@StewEucen 

Suggest: `actualTable` → `actualValues`

2022-05-08 14:12 UTC, lisadhl commented on lib/setup.js
> +      return (expectedArgs) =>
@StewEucen 

Suggest: `expectedArgs` → `expectedValues`

2022-05-08 14:12 UTC, lisadhl commented on lib/setup.js
> +        })
@StewEucen 

How about to use Ternary?

```js
    return expectProxyCreators[propertyName]
      ? expectProxyCreators[propertyName](actualTable)
      : (expectedArgs) =>
          createExpectCaller({
            actualTable,
            expectedArgs,
            propertyChains: [propertyName]
          })
```

2022-05-08 14:12 UTC, lisadhl commented on lib/setup.js
> +        })
@StewEucen 

To eliminate duplication, how about doing the following refactoring?

```js
function createExpectProxyAsPromise ({
  actualTable,
  promiseMethod,
}) {
  return new Proxy(expect, {
    get (_, matcher) {
      if (matcher === 'not') {
        return new Proxy(expect, {
          get (_, matcher) {
            return createPromise(matcher, true)
          }
        })
      }

      return createPromise(matcher)
    }
  })

  function createPromise(matcher, isNot = false) {
    const propertyChains = [
      promiseMethod,
      matcher
    ]

    if (isNot) {
      propertyChains.splice(1, 0, 'not')
    }

    return (expectedArgs) => Promise.allSettled(
      createExpectCaller({
        actualTable,
        expectedArgs,
        propertyChains
      })
    )
  }
}
```

2022-05-08 14:22 UTC, StewEucen commented on lib/setup.js
> +  expect.each = (actualTable) => new Proxy(expect, {
@lisadhl 

## English

* On the official Jest website, variables that we write as `cases` in test case are expressed as `table`. Therefore, we think table is appropriate here.

* In future, I am going to change `cases` to `table` in tests of our application.

## 日本語

* Jest 公式サイトでは、我々が cases と書いている変数を table と表現しています。従って、此処では table が相応しいと考えています。

* 今後のアプリケーションでは、我々のテストでも table に変えていこうと考えています。

2022-05-08 14:25 UTC, StewEucen commented on lib/setup.js
> +      return (expectedArgs) =>
@lisadhl 

* I am going to change as your suggestiion. Thank you :)

2022-05-08 14:30 UTC, StewEucen commented on lib/setup.js
> +        })
@lisadhl 

## English

* We preferred to avoid the ternary operator in all cases, and thought it should be used only when "switching between homogeneous values". In this case, writing an if statement has the advantage of clarifying the intent of "do not process the value.

## 日本語

* 三項演算子はあらゆるケースで回避するのが好く、使うケースは「同質の値を切り替える」場合に限られるべきだと考えました。此のケースでは、if 文で書くことにより「値を加工しない」と云う意図が明確になる利点があります。

2022-05-08 14:40 UTC, lisadhl commented on lib/setup.js
> +  expect.each = (actualTable) => new Proxy(expect, {
@StewEucen 

**_Table_** gives the impression that it is a two-dimensional data structure.

2022-05-08 14:47 UTC, StewEucen commented on lib/setup.js
> +  expect.each = (actualTable) => new Proxy(expect, {
@lisadhl 

* You are right.

* "parameter of `describe.each()` and `test.each()` should have two-dimensional data structure" is the intention of Jest.
  > "`describe.each()` と `test.each()` のパラメータは2次元のデータ構造を持つべきである" というのが、Jestの意図です。
  
* However, `expect.each()` require one-dimensional data structure only. I am going to change to your suggestion.

* Thank you, 我給你🍙

2022-05-08 14:52 UTC, StewEucen commented on lib/setup.js
> +        })
* Apply refactored modifications to simplify replication.
  > 複製を簡単にする為、リファクタリング済みの修整を適用します。
  
```
function createExpectProxyAsPromise ({
  actualValues,
  promiseMethod,
}) {
  return new Proxy(expect, {
    get (_, matcher) {
      if (matcher === 'not') {
        return new Proxy(expect, {
          get (_, matcher) {
            return createPromise(matcher, true)
          }
        })
      }

      return createPromise(matcher)
    }
  })

  function createPromise (matcher, isNot = false) {
    const propertyChains = [
      promiseMethod,
      matcher
    ]

    if (isNot) {
      propertyChains.splice(1, 0, 'not')
    }

    return (expectedValues) => Promise.allSettled(
      createExpectCaller({
        actualValues,
        expectedValues,
        propertyChains
      })
    )
  }
}
```

2022-05-08 15:00 UTC, StewEucen commented on lib/setup.js
> +        })
* Current code.

```
function createExpectProxyAsPromise ({
  actualValues,
  promiseMethod,
}) {
  return new Proxy(expect, {
    get (_, matcher) {
      if (matcher === 'not') {
        return new Proxy(expect, {
          get (_, matcher) {
            return (expectedValues) => Promise.allSettled(
              createExpectCaller({
                actualValues,
                expectedValues,
                propertyChains: [
                  promiseMethod,
                  'not',
                  matcher
                ]
              })
            )
          }
        })
      }

      return (expectedValues) => Promise.allSettled(
        createExpectCaller({
          actualValues,
          expectedValues,
          propertyChains: [
            promiseMethod,
            matcher
          ]
        })
      )
    }
  })
}
```

2022-05-08 15:07 UTC, lisadhl requested changes

2022-05-08 15:07 UTC, lisadhl commented on tests/__tests__/not/toBe.js
> +    const expectedTable = Array(actualValues.length).fill(-1000)
@StewEucen 

`expectedTable` → `expectedValues`

2022-05-08 15:21 UTC, StewEucen commented on lib/setup.js
> +        })
@lisadhl (cc: @JYama321)

* Your code had worked, I confirmed. And my opinion as follows:

## English

* I have read a saying by one of the programmer on a long time ago.
  ```
  I think that all bugs are created where the conditional branches like if-statement are written.
  ```
  
* I learnt by the saying as follows:
   1. Adding more references to a condition, it make us many places to require attention during repair. The maintainability of the code will be compromised, because the repairer will have to completely fix all the references.
   2. The code that determines a condition only once and in one place is the most resistant to bugs and modifications.


## 日本語

* 昔、プログラマの誰かから私が聴いた言葉があります。
  ```
  全てのバグは、`if` 文のような条件分岐が書かれた場所で生まれるんじゃないかと考えている
  ```

* 其の言葉から、以下の様に私は学びました。
   1. ある条件の参照箇所を増やすと、修整時に注意しなければならない箇所が増えてしまう。 修整者は、全部の参照箇所を完璧になおさなければならず、メンテナンス性を損なう。
   2. ある条件を一回だけ一箇所で判定するコードは、バグや修整に対して最も強いコードになる。

2022-05-08 15:45 UTC, StewEucen commented on lib/setup.js
> +      }
@lisadhl (cc: @JYama321, @EG-easy )

## English

* By analogy with `describe.each()` and `test.each()`, I believe that `expect.each()` is a natural reach for many developers.

* Of course, I am well aware that it is bad to modify objects defined by external libraries. However, I dared to implement it in a bad way for the following reasons.
  ```
  After publishing this repository as OSS, I am going to propose this extension to Jest official.
  ```

* If by some chance Jest incorporates this extension in the future, I dare to design it this way to minimize the modification of the past code at that time.

* All `expect.xxx` members are not a matcher, they are tools to help matcher, I undertood.

## 日本語

* `describe.each()` と `test.each()` から類推して、`expect.each()` は多くの開発者が自然に到達できると考えています。

* 勿論、外部ライブラリが定義しているオブジェクトを改変するのが悪い事は十分に承知しています。其れでも敢えて悪い方法で実装したのは、以下の理由からでした。
  ```
  此のリポジトリを OSS として公開した後で、Jest 公式に対して此の拡張を提案しようと考えている。
  ```

* もしも万が一、将来に此の拡張を Jest が取り込んだとして。其の後で、過去のコードの修整を最小限にするために、敢えて此の設計にしました。

* すべての `expect.xxx` のメンバーは matcher ではなく、matcher を補助するツールである、と私は理解しています。

2022-05-08 15:47 UTC, StewEucen commented on tests/__tests__/not/toBe.js
> +    const expectedTable = Array(actualValues.length).fill(-1000)
@lisadhl 

* Thank you, changes :)

2022-05-08 17:27 UTC, StewEucen reviewed
@lisadhl 

* Refactored `createExpectCaller()` simply. If it is OK, please reaction to this conversation.

2022-05-08 17:27 UTC, StewEucen commented on lib/setup.js
> +}
@lisadhl 

* Refactored `createExpectCaller()` simply.

```
// original code
function createExpectCaller ({
  actualValues,
  expectedValues,
  propertyChains,
}) {
  return actualValues
    .map((it, index) =>
      [it, expectedValues[index]]
    )
    .map(([actual, expected]) =>
      propertyChains.reduce(
        (accumulator, it) => accumulator[it],
        expect(actual)
      )(expected)
    )
}
```

↓

```
// refactered
function createExpectCaller ({
  actualValues,
  expectedValues,
  propertyChains,
}) {
  return actualValues
    .map(value =>
      propertyChains.reduce(
        (receiver, it) => receiver[it],
        expect(value)
      )
    )
    .map((matcher, index) =>
      matcher(expectedValues[index])
    )
}
```

2022-05-08 17:28 UTC, StewEucen commented on lib/setup.js
> +}
@lisadhl 

* It is a calm code now.
  > 今は落ち着いたコードになってます。

2022-05-08 20:56 UTC, lisadhl commented on lib/setup.js
> +}
@StewEucen 

The refactor is good! 👍

2022-05-08 21:00 UTC, lisadhl approved these changes
🍵

2022-05-08 21:00 UTC, merged